In [61]:
import pandas as pd

columns = ["Title","Date"]
df = pd.read_csv("./jobs.csv", names =columns, on_bad_lines='skip')

df.head(20)

                                   Title        Date
0                Senior Python Developer  2021-04-08
1                        Energy engineer  2021-04-08
2                        Legal executive  2021-04-08
3                 Fitness centre manager  2021-04-08
4                        Product manager  2021-04-08
5              Medical technical officer  2021-04-08
6                Physiological scientist  2021-04-08
7                       Textile designer  2021-04-08
8               Television floor manager  2021-04-08
9               Waste management officer  2021-04-08
10            Software Engineer (Python)  2021-04-08
11                           Interpreter  2021-04-08
12                             Architect  2021-04-08
13                         Meteorologist  2021-04-08
14                Audiological scientist  2021-04-08
15  English as a second language teacher  2021-04-08
16                               Surgeon  2021-04-08
17                       Equities trader  2021-04-08
18                  Newspaper journalist  2021-04-08
19                    Materials engineer  2021-04-08